import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "./globals.css";
import styles from "@/app/ui/scrollbarHide.module.css";
import NavBar from "@/app/ui/home/navbar";
const public_sans = Public_Sans({
  subsets: ["latin"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`w-full ${public_sans} antialiased overflow-scroll ${styles.scrollbarhidden}`}
      >
        <>
          <NavBar />
          <main className="w-full">{children}</main>
        </>
      </body>
    </html>
  );
}
